export enum State {
	AC = 'Acre',
	AL = 'Alagoas',
	AP = 'Amapá',
	AM = 'Amazonas',
	BA = 'Bahia',
	CE = 'Ceará',
	DF = 'Distrito Federal',
	ES = 'Espírito Santo',
	GO = 'Goiás',
	MA = 'Maranhão',
	MT = 'Mato Grosso',
	MS = 'Mato Grosso do Sul',
	MG = 'Minas Gerais',
	PA = 'Pará',
	PB = 'Paraíba',
	PR = 'Paraná',
	PE = 'Pernambuco',
	PI = 'Piauí',
	RJ = 'Rio de Janeiro',
	RN = 'Rio Grande do Norte',
	RS = 'Rio Grande do Sul',
	RO = 'Rondônia',
	RR = 'Roraima',
	SC = 'Santa Catarina',
	SP = 'São Paulo',
	SE = 'Sergipe',
	TO = 'Tocantins',
}

export const States = Object.values(State);

export type City = {
	name: string;
};

export const Cities: Record<State, City[]> = {
	[State.AC]: [{ name: 'Rio Branco' }],
	[State.AL]: [{ name: 'Maceió' }],
	[State.AP]: [{ name: 'Macapá' }],
	[State.AM]: [{ name: 'Manaus' }],
	[State.BA]: [{ name: 'Salvador' }],
	[State.CE]: [{ name: 'Fortaleza' }],
	[State.DF]: [{ name: 'Brasília' }],
	[State.ES]: [{ name: 'Vitória' }],
	[State.GO]: [{ name: 'Goiânia' }],
	[State.MA]: [{ name: 'São Luís' }],
	[State.MT]: [{ name: 'Cuiabá' }],
	[State.MS]: [{ name: 'Campo Grande' }],
	[State.MG]: [{ name: 'Belo Horizonte' }],
	[State.PA]: [{ name: 'Belém' }],
	[State.PB]: [{ name: 'João Pessoa' }],
	[State.PR]: [{ name: 'Curitiba' }],
	[State.PE]: [{ name: 'Recife' }],
	[State.PI]: [{ name: 'Teresina' }],
	[State.RJ]: [{ name: 'Rio de Janeiro' }],
	[State.RN]: [{ name: 'Natal' }],
	[State.RS]: [{ name: 'Porto Alegre' }],
	[State.RO]: [{ name: 'Porto Velho' }],
	[State.RR]: [{ name: 'Boa Vista' }],
	[State.SC]: [{ name: 'Florianópolis' }],
	[State.SP]: [{ name: 'São Paulo' }],
	[State.SE]: [{ name: 'Aracaju' }],
	[State.TO]: [{ name: 'Palmas' }],
};
