services:

  db:
    image: mysql:8.0
    container_name: carros-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password

  api:
    image: carros-api
    container_name: carros-api
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:3000"
    environment:
      - DB_PORT=3306
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /usr/src/app/src
        - action: sync+restart
          path: ./backend/.env
          target: /usr/src/app/.env
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/tsconfig.json
    depends_on:
      - db

  app:
    image: carros-app
    container_name: carros-app
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT}:4200"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    develop:
      watch:
      - action: rebuild
        path: ./frontend/package.json
      - action: rebuild
        path: ./frontend/tsconfig.json
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carros-phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    depends_on:
      - db

volumes:
  db-data:
    driver: local
  localstack-data:
    driver: local
